name: Destroy ECS Module

on:
  workflow_dispatch:

jobs:
  terraform:
    name: 'Terraform Destroy'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_ANDY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ANDY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN_ANDY }}
          aws-region: eu-west-3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Terraform Init
        run: terraform init
        working-directory: modulo_ecs

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        working-directory: modulo_ecs